# Generated by Django 3.1.5 on 2021-01-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('descripiton', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
